name: TEC_LncMir

dependencies:
  - pip
  - python=3.8
  - biopython=1.76
  - h5py
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - setuptools=58.2.0
  - tqdm
  - attrdict
  - einops
  - regex
